# NumPy

 NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [17]:
import numpy as np


# Numpy Arrays

In [18]:
my_list=[1,2,3,4,5]

In [47]:
arr=np.array(my_list,dtype='int64')

In [48]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [23]:
my_arr=[1,2,3],[4,5,6],[7,8,9]

In [24]:
np.array(my_arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr.shape

(5,)

In [39]:
np.arange(20,30)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
np.arange(0,13,3)

array([ 0,  3,  6,  9, 12])

In [31]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.random.rand(5)

array([0.30536415, 0.97330246, 0.34068651, 0.1505527 , 0.11801282])

In [37]:
np.random.randn(2)

array([ 0.79031373, -0.81408626])

In [38]:
np.random.randn(5,5)

array([[-0.75402384, -0.07152273,  0.52104006,  0.3960553 , -0.56963551],
       [-0.12970231, -1.29431838,  0.44386315,  0.10525469, -1.04157125],
       [ 1.18597912, -0.17969966,  0.15320594, -0.64055692,  1.49532631],
       [ 1.19904727, -0.11650423,  0.62547147,  0.35425289, -0.0917306 ],
       [-0.01801912, -1.1213317 ,  0.2044353 , -0.56429784,  0.02779586]])

### array reshape

In [41]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [44]:
arr.max()

5

In [46]:
arr.argmax()

4

In [32]:
arr.shape

(5,)

In [49]:
arr.dtype

dtype('int64')

### Numpy indexing and selection

In [50]:
arr= np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr[2]

2

In [53]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[5:-1]

array([5, 6, 7, 8, 9])

In [54]:
arr[0:5]=100

In [55]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [56]:
arr=np.arange(0,11)

In [66]:
arr

array([42, 42, 42, 42, 42, 42,  6,  7,  8,  9, 10])

In [58]:
slic_arr=arr[0:6]

In [59]:
slic_arr

array([0, 1, 2, 3, 4, 5])

In [60]:
slic_arr[:]

array([0, 1, 2, 3, 4, 5])

In [64]:
slic_arr[:]=42

In [65]:
slic_arr

array([42, 42, 42, 42, 42, 42])

In [68]:
arr_copy=arr.copy()

In [69]:
arr_copy

array([42, 42, 42, 42, 42, 42,  6,  7,  8,  9, 10])

In [70]:
arr_copy[:]=100

In [71]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [72]:
arr

array([42, 42, 42, 42, 42, 42,  6,  7,  8,  9, 10])

In [73]:
arr_2d=np.array([[5,4,6],[20,25,30],[23,40,45]])

In [74]:
arr_2d

array([[ 5,  4,  6],
       [20, 25, 30],
       [23, 40, 45]])

In [77]:
arr_2d[1,0]

20

In [78]:
arr_2d[:2,1:]

array([[ 4,  6],
       [25, 30]])

In [83]:
arr_2d[:2,:-1]

array([[ 5,  4],
       [20, 25]])

### conditional selection 

In [84]:
arr= np.arange(0,11)

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [87]:
bool_arr=arr>5

In [88]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [89]:
arr[arr<3]

array([0, 1, 2])

In [90]:
arr_2d= np.arange(50).reshape(5,10)

In [98]:
arr_2d>2
arr_2d[arr_2d<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr_2d[1:4,2:5]>10

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])